### ISSUE TITLE
Is the current code in a state where it cannot be executed?

### ISSUE THREAD

**Issue by SangbaekYoo** [eigenvivek/DiffPose#43]
Thank you for sharing such an amazing program!
I'd like to run the Diffpose code on my PC for testing, but I'm encountering the following error:

```
ImportError: cannot import name 'convert' from 'diffdrr.utils' ...
```

In the diffdrr code, I found that functions like 'convert' or 'se3_exp_map' are not currently located in utils.py within diffdrr, but rather in pose.py. This leads me to believe that some modifications have been made.

I tried to make some modifications myself to get it running, but I'm currently stuck because I can't figure out what the Transform3d function is.

If the current code is still under development, I will give up but, if there is my mistake, please give feedback to solve this problem.

Best regards,
Sangbaek

**Comment by eigenvivek** [comment]
Hi Sangbaek, you're right that DiffPose is not compatible with the latest version of DiffDRR. However, it should work with DiffDRR 0.3.9. Are you using that version?

**Comment by SangbaekYoo** [comment]
Problem is solved! Thank you.

One another question is that, how can I reach fast optimization. this is similar with https://github.com/eigenvivek/DiffPose/issues/41#issue-2560679894. 
When I used diffdrr and mNCC optimization to my CT file, running time was long.(This CT file is not large.)
I followed this registration code(https://github.com/eigenvivek/DiffDRR/blob/main/notebooks/tutorials/registration.ipynb) and set parameters from the diffpose paper.(I also found these parameters in the diffpose code.)

But I never reached to short optimization time if I do not give stop condition.
For example, if iteration is set to 250, full optimization time is 7~8 second. I cannot reach to such 2 second given in the paper.

I am using GPU Titan XP and RTX 3090. Is this just hardware issue or should I change some code setting?

**Comment by eigenvivek** [comment]
Great!
A few things to speed up optimization:
- If you can get a more accurate initial pose estimate (either from a pose regression neural network or a manual initial estimate), iterative optimization will require less iterations
- You can use the sparse rendering approach to decrease the number of pixels you need to render with each pixel (I never conducted a thorough sensitivity analysis of % of pixels rendered versus registration accuracy, but you might be able to get away with very sparse rendering depending on your problem)
- Use a early stopping criterion (e.g., stop on plateau) - usually the last ~100 iterations of the total 250 are spent making very incremental progress

If you can offload registration with the newest version of DiffDRR, you can also use the new trilinear rendering backend, which is quite a bit faster than Siddon's without sacrificing much accuracy.

**Comment by SangbaekYoo** [comment]
Thank you very much for your advice. I really appreciate it!
